name: Upload coverage reports to Codecov

on:
  push: # This workflow will run on pushes to the repository

jobs:
  upload-coverage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          #python-version: 3.9.18 
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt -vvv


      - name: Run Unit Tests and Generate Coverage Reports
        run: |
            pytest --cov=./UnitTesting

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
