name: Syntax Checker

on:
  push:
    branches: [New_G50-WolfTrack7.0]
  pull_request:
    branches: [New_G50-WolfTrack7.0]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint
        run: pylint app.py
